jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.jobs_list, name='jobs'),
]

jobs/models.py
from django.db import models
from django.contrib.humanize.templatetags.humanize import intcomma

class Job(models.Model):
    title = models.CharField(max_length=300, unique=False, verbose_name='Заголовок', blank=True)

    salary_from = models.IntegerField(null=True, blank=True, verbose_name='Зарплата от')
    salary_up_to = models.IntegerField(null=True, blank=True, verbose_name='Зарплата до')
    CURRENCY_OPTIONS = (
        ('RUR', 'руб.'),
        ('USD', 'USD'),
        ('EUR', 'EUR')
    )
    salary_currency = models.CharField(max_length=3, choices=CURRENCY_OPTIONS, verbose_name='Валюта',
                                       default='RUR', blank=True)

    company = models.ForeignKey('Employer', null=True, on_delete=models.CASCADE, verbose_name='Работодатель')
    city = models.ForeignKey('City', null=True, on_delete=models.SET_NULL, verbose_name='Город', blank=True)
    remote = models.BooleanField(default=False, verbose_name='Можно удаленно', blank=True)
    experience = models.CharField(max_length=100, blank=True, verbose_name='Требуемый опыт')

    EMPLOYMENT_STATUS = (
        ('f', 'Полная занятость'),
        ('p', 'Частичная занятость'),
        ('i', 'Стажировка'),
        ('p', 'Проектная работа'),
        ('v', 'Волонтерство'),
    )
    type_of_employment = models.CharField(max_length=1, choices=EMPLOYMENT_STATUS,
                                          verbose_name='Тип занятости', default=None)

    description = models.TextField(verbose_name='Описание')
    skills = models.ManyToManyField('Skill', null=True, blank=True, verbose_name='Навыки')
    published = models.DateTimeField(verbose_name='Дата публикации')
    hh_id = models.IntegerField(unique=True, verbose_name='HH ID')
    archived = models.BooleanField(default=False)
    page_views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def display_skills(self):
        return [skill.name for skill in self.skills.all()]

    def short_description(self):
        return self.description[:140] + '...'

    def display_salary(self):
        if self.salary_from and self.salary_up_to:
            return f'{intcomma(self.salary_from)}-{intcomma(self.salary_up_to)} {self.get_salary_currency_display()}'
        elif self.salary_from:
            return f'от {intcomma(self.salary_from)} {self.get_salary_currency_display()}'
        elif self.salary_up_to:
            return f'до {intcomma(self.salary_up_to)} {self.get_salary_currency_display()}'
        else:
            return 'З/п не указана'

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'


class City(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Город')
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ['name']

class Employer(models.Model):
    name = models.CharField(max_length=300, unique=True, verbose_name='Работодатель')
    logo = models.URLField(max_length=500, null=True, verbose_name='Логотип', blank=True)
    description = models.TextField(null=True, verbose_name='Описание', blank=True)
    website = models.URLField(null=True, verbose_name='Сайт', blank=True)
    vacancies = models.ManyToManyField('Job', null=True, blank=True, verbose_name='Вакансии')

    page_views = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Работодатель'
        verbose_name_plural = 'Работодатели'

class Skill(models.Model):
    name = models.CharField(max_length=300, unique=True, verbose_name='Навык')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Навык'
        verbose_name_plural = 'Навыки'

jobs/forms.py
from django import forms
from jobs.models import Job, Skill,City

top_skills = ['Java', 'C', 'Python', 'C++', 'C#', 'JavaScript', 'PHP', 'Objective-C',
                  'R', 'Swift', 'TypeScript', 'Ruby', 'HTML', 'CSS', 'Scala',
                  'Go', 'Kotlin', 'Matlab', 'Ruby On Rails']

salary_choices = [
                ('true', 'Указана'),
                ('30000', 'от 30 000 руб.'),
                ('60000', 'от 60 000 руб.'),
                ('120000', 'от 120 000 руб.')
                 ]


class JobFrom(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['skills'].queryset = Skill.objects.filter(name__in=top_skills)

    class Meta:
        model = Job
        labels = ''
        fields = ['type_of_employment', 'city', 'remote', 'title', 'salary_from', 'skills']

        widgets = {
            'type_of_employment' : forms.CheckboxSelectMultiple(),
            'city' : forms.Select(attrs={'class': 'nice-select wide', 'style' : 'display: none;'}),
            'remote' : forms.CheckboxInput(),
            'title' : forms.TextInput(attrs={'placeholder' : 'Поиск по названию...', 'class': 'w-100'}),
            'salary_from' : forms.RadioSelect(choices=salary_choices),
            'skills' : forms.CheckboxSelectMultiple()
                    }

class EmployerForm(forms.Form):
    search = forms.CharField(required=False,
                             widget=forms.TextInput(attrs={'placeholder' : 'Название компании...',
                                                           'class': 'w-100'})
                             )
    city = forms.ModelChoiceField(queryset=City.objects.all(),
                                  widget=forms.Select(attrs={'class': 'nice-select wide'}),
                                  required=False
                                  )

    remote = forms.BooleanField(required=False)
    
    skills = forms.ModelChoiceField(required=False,
                                    queryset=Skill.objects.filter(name__in=top_skills),
                                    widget=forms.CheckboxSelectMultiple(),
                                    empty_label=None)

class MainPageForm(JobFrom):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].empty_label = 'Город'
        self.fields['title'].widget.attrs['placeholder'] = 'Какую работу вы ищете?'
        self.fields['salary_from'].widget = forms.Select(attrs={'class': 'nice-select wide'})
        self.fields['salary_from'].widget.choices = [(None, 'Зарплата')] + salary_choices

jobs/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Q
from django.views.generic import DetailView, ListView
from django.db.models import Count
from .models import Job, Employer,City
from .forms import JobFrom, EmployerForm, MainPageForm
from accounts.forms import UserRegistrationForm, UserLoginForm
from .utils import get_user_search_params, create_paginate_link


def jobs_list(request):
    context = dict()
    register_form = UserRegistrationForm
    login_form = UserLoginForm

    city = request.GET.get('city')
    type_of_employment = request.GET.getlist('type_of_employment')
    remote = request.GET.get('remote')
    search_field = request.GET.get('title')
    salary_from = request.GET.get('salary_from')
    skills = request.GET.getlist('skills')

    jobs = Job.objects.filter(archived=False)

    search_params = {}

    if type_of_employment:
        jobs = jobs.filter(type_of_employment__in=type_of_employment)
        search_params['type_of_employment'] = type_of_employment

    if city and not remote:
        jobs = jobs.filter(city=city)
        search_params['city'] = city
    if remote and not city:
        jobs = jobs.filter(remote=True)
        search_params['remote'] = remote
    if city and remote:
        jobs = jobs.filter(Q(city=city)|Q(remote=True))
        search_params['city'] = city
        search_params['remote'] = remote

    if search_field:
        jobs = jobs.filter(title__contains=search_field)
        search_params['search_field'] = search_field
    if skills:
        jobs = jobs.filter(skills__in=skills)
        search_params['skills'] = skills

    if salary_from == 'true':
        jobs = jobs.filter(Q(salary_from__isnull=False) | Q(salary_up_to__isnull=False))
        search_params['salary_from'] = salary_from
    elif salary_from:
        salary_rub_qs = Job.objects.filter(
                                Q(salary_from__gte=salary_from) |
                                Q(salary_up_to__gte=salary_from)
                                ).filter(salary_currency='RUR')

        salary_euro = int(salary_from)/90
        salary_usd = int(salary_from)/80

        salary_total_qs = salary_rub_qs.union(
            Job.objects.filter(Q(salary_from__gte=salary_euro) |
                               Q(salary_up_to__gte=salary_euro)
                               ).filter(salary_currency='EUR'),
            Job.objects.filter(Q(salary_from__gte=salary_usd) |
                               Q(salary_up_to__gte=salary_usd)
                               ).filter(salary_currency='USD')
        )

        jobs = jobs.intersection(salary_total_qs)
        search_params['salary_from'] = salary_from

    paginator = Paginator(jobs.distinct().order_by('-published'), 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.user.is_authenticated:
        user_params = get_user_search_params(request)
        user_params_link = create_paginate_link(user_params)
        context['user_params_link'] = user_params_link


    form = JobFrom(initial=search_params)

    paginate_link = create_paginate_link(search_params)

    context.update({'jobs': page_obj, 'form': form, 'paginate_link' : paginate_link,
               'register_form' : register_form, 'login_form' : login_form})

    return render(request, 'jobs/job-listing.html', context)


class JobDetailView(DetailView):
    model = Job

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['register_form'] = UserRegistrationForm
        context['login_form'] = UserLoginForm
        if self.request.user.is_authenticated:
            user_params = get_user_search_params(self.request)
            user_params_link = create_paginate_link(user_params)
            context['user_params_link'] = user_params_link

        return context

    def get_object(self):
        obj = super().get_object()
        num_visits = self.request.session.get(f'job_{obj.id}_visits', 0)
        self.request.session[f'job_{obj.id}_visits'] = num_visits + 1
        if self.request.session[f'job_{obj.id}_visits'] == 1:
            obj.page_views += 1
            obj.save()
        return obj



class EmployerListView(ListView):
    model = Employer
    template_name = 'jobs/employer-listing.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Employer.objects.filter(vacancies__isnull=False) \
                        .annotate(jobs_count=Count('vacancies')) \
                        .order_by('-jobs_count')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['register_form'] = UserRegistrationForm
        context['login_form'] = UserLoginForm

        search_field = self.request.GET.get('search')
        city = self.request.GET.get('city')
        remote = self.request.GET.get('remote')
        skills = self.request.GET.getlist('skills')

        search_params = {}

        queryset = self.get_queryset()

        if search_field:
            queryset = queryset.filter(Q(name__contains=search_field) |
                                       Q(name__contains=search_field.capitalize()) |
                                       Q(name__contains=search_field.upper())
                                       )
            search_params['search_field'] = search_field
        if city and not remote:
            queryset = queryset.filter(vacancies__city=city)
            search_params['city'] = city
        if remote and not city:
            queryset = queryset.filter(vacancies__remote=True)
            search_params['remote'] = remote
        if city and remote:
            queryset = queryset.filter(Q(vacancies__city=city) | Q(vacancies__remote=True))
            search_params['city'] = city
            search_params['remote'] = remote
        if skills:
            queryset = queryset.filter(vacancies__skills__in=skills)
            search_params['skills'] = skills

        paginator = Paginator(queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['object_list'] = page_obj

        context['form'] = EmployerForm(initial=search_params)

        paginate_link = create_paginate_link(search_params)

        context['paginate_link'] = paginate_link

        if self.request.user.is_authenticated:
            user_params = get_user_search_params(self.request)
            user_params_link = create_paginate_link(user_params)
            context['user_params_link'] = user_params_link

        return context

class EmployerDetailView(DetailView):
    model = Employer
    #extra_context = {'register_form' : UserRegistrationForm, 'login_form' : UserLoginForm}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['register_form'] = UserRegistrationForm
        context['login_form'] = UserLoginForm
        if self.request.user.is_authenticated:
            user_params = get_user_search_params(self.request)
            user_params_link = create_paginate_link(user_params)
            context['user_params_link'] = user_params_link
        return context

    def get_object(self):
        obj = super().get_object()
        num_visits = self.request.session.get(f'emp_{obj.id}_visits', 0)
        self.request.session[f'emp_{obj.id}_visits'] = num_visits + 1
        self.request.session.modified = True
        if self.request.session[f'emp_{obj.id}_visits'] == 1:
            obj.page_views += 1
            obj.save()
        return obj

def index(request):
    context = dict()

    full_time_jobs = Job.objects.filter(archived=False, type_of_employment='f',
                                        remote=False).order_by('-published')[:4]

    remote_jobs = Job.objects.filter(archived=False, remote=True).order_by('-published')[:4]

    intern_jobs = Job.objects.filter(archived=False, type_of_employment='i',
                                        remote=False).order_by('-published')[:4]

    employers = Employer.objects.filter(vacancies__isnull=False, logo__isnull=False) \
                        .annotate(jobs_count=Count('vacancies')) \
                        .order_by('-jobs_count')
    register_form = UserRegistrationForm
    login_form = UserLoginForm
    job_form = MainPageForm

    jobs_total = Job.objects.filter(archived=False).count()
    employers_total = Employer.objects.filter(vacancies__isnull=False).distinct().count()
    cities = City.objects.all().count()

    if request.user.is_authenticated:
        user_params = get_user_search_params(request)
        user_params_link = create_paginate_link(user_params)
        context['user_params_link'] = user_params_link

    context.update({'full_time_jobs' : full_time_jobs, 'remote_jobs' : remote_jobs,
               'intern_jobs': intern_jobs, 'employers' : employers,
               'register_form' : register_form, 'login_form' : login_form,
               'jobs_total' : jobs_total, 'employers_total' : employers_total,
               'cities' : cities, 'job_form' : job_form})

    return render(request, 'jobs/index.html', context)

jobs/templates/jobs/employer_detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block title %}Вакансии в компании {{ object.name }} для начинающих IT-специалистов | Hello Junior{% endblock %}
{% block breadcrumb %}
        <!-- Breadcrumb Section Start -->
        <div class="breadcrumb-section section pt-60 pt-sm-50 pt-xs-40">
            <div class="container sb-border-two pb-60 pb-sm-50 pb-xs-40">
                <div class="row">
                    <div class="col-12">
                        <div class="page-breadcrumb-content mb-40">
                            <ul class="page-breadcrumb">
                                <li><a href="{% url 'index' %}">Главная</a></li>
                                <li><a href="{% url 'employers' %}">Работодатели</a></li>
                                <li>{{ object.name }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-lg-7">
                        <div class="employer-head-info">
                            <div class="employer-logo">
                                {% if object.logo %}
                                <a href="employer-details.html#"><img src="{{ object.logo }}" alt=""></a>
                                {% else %}
                                <img src="{% static 'assets/images/companies_logo/no-logo.jpg' %}" alt="Нет логотипа">
                                {% endif %}
                            </div>
                            <div class="employer-content">
                                <h1 class="employer-name">{{ object.name }}</h1>
                                <ul class="employer-meta">
                                    <li class="view-employer"><i class="lnr lnr-eye"></i>{{ object.page_views }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Breadcrumb Section Start -->
{% endblock %}

{% block content %}
        <!-- Employer Details Section Start -->
        <div class="employer-details-section section pt-120 pt-lg-100 pt-md-80 pt-sm-50 pt-xs-40 pb-120 pb-lg-100 pb-md-80 pb-sm-60 pb-xs-50">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 order-lg-2 order-2 mt-sm-60 mt-xs-50">
                        <div class="sidebar-wrapper-three">
                            <div class="common-sidebar-widget sidebar-three">
                                <div class="sidebar-meta sidebar-meta-two">

                                    <!-- Single Meta Field Start -->
                                    <div class="single-meta-field meta-field-two">
                                        <div class="field-label">
                                            <i class="lnr lnr-users"></i>
                                            <span>Открыто вакансий: </span>
                                        </div>
                                        <div class="field-value">{{ object.vacancies.count }}</div>
                                    </div>
                                    <!-- Single Meta Field End -->

                                    <!-- Single Meta Field Start -->
                                    <div class="single-meta-field meta-field-two">
                                        <div class="field-label">
                                            <i class="lnr lnr-earth"></i>
                                            <span>Сайт: </span>
                                        </div>
                                        <div class="field-value">
                                            {% if object.website %} {{ object.website }}
                                            {% else %} не указан
                                            {% endif %}
                                        </div>
                                    </div>
                                    <!-- Single Meta Field End -->
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-8 order-lg-1 order-1 pr-55 pr-md-15 pr-sm-15 pr-xs-15">

                        <div class="employer-main-content">
                            <div class="field-description">
                                {% if object.description %}
                                {{ object.description|safe }}
                                {% else%}
                                <p>Компания пока не указала описание.</p>
                                {% endif %}
                            </div>

                            <div class="job-area mt-60">
                                <div class="job-container">
                                    <h3 class="title">Вакансии компании {{ object.name }}:</h3>
                                    <div class="row">
                                    {% for job in object.job_set.all %}
                                        <div class="col-lg-12">
                                            <!-- Single Job Start  -->
                                            <div class="single-job style-two">
                                                <div class="info-top">
                                                    <div class="job-info">
                                                        <div class="job-info-inner">
                                                            <div class="job-info-top">
                                                                <div class="saveJob for-listing">
                                                                    {% if job.remote %}
                                                                    <span class="featured-label">Удалённо</span>
                                                                    {% endif %}
                                                                    <p class="job-type-label ml-20 mr-20">{{ job.get_type_of_employment_display }}</p>
                                                                    {% if user.is_authenticated %}
                                                                    <form action="{% url 'add_remove' id=job.id %}" method="post">{% csrf_token %}
                                                                    <button class="save-job">
                                                                        {% if job in user.favorites.all %}
                                                                        <i class="fas fa-heart" style="color:red"></i>
                                                                        {% else %}
                                                                        <i class="far fa-heart"></i>
                                                                        {% endif %}
                                                                        <input type="hidden" name="url_from" value="{{ request.get_full_path }}">
                                                                    </button>
                                                                    </form>
                                                                    {% else %}
                                                                    <a class="save-job" href="#quick-view-modal-container" data-toggle="modal">
                                                                        <i class="far fa-heart"></i>
                                                                    </a>
                                                                    {% endif %}
                                                                </div>
                                                                <div class="title-name">
                                                                    <h5 class="job-title">
                                                                        <a href="{% url 'job_detail' pk=job.id %}">{{ job.title }}</a>
                                                                    </h5>
                                                                </div>
                                                            </div>
                                                            <div class="job-meta-two">
                                                                <div class="field-salary_from">
                                                                    <i class="gj-icon gj-icon-money"></i>
                                                                    {{ job.display_salary }}
                                                                </div>
                                                                <div class="field-datetime"><i class="lnr lnr-clock"></i>{{ job.published|naturaltime }}</div>
                                                                <div class="field-map"><i class="lnr lnr-map-marker"></i>{{ job.city }}</div>
                                                            </div>
                                                            {% if job.skills %}
                                                            <div class="job-skill-tag">
                                                                {% for skill in job.skills.all %}
                                                                <a href="{% url 'jobs' %}?skills={{ skill.id }}">{{ skill.name }}</a>
                                                                {% endfor %}
                                                            </div>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- Single Job End -->
                                        </div>
                                    {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
        <!-- Employer Details Section End -->
{% endblock %}